# Generated by Django 6.0.3 on 2026-03-16 21:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('cycling', 'Cycling'), ('running', 'Running'), ('yoga', 'Yoga'), ('strength', 'Strength Training'), ('mindfulness', 'Mindfulness'), ('nutrition', 'Nutrition'), ('outdoors', 'Outdoors'), ('swimming', 'Swimming'), ('hiking', 'Hiking'), ('pilates', 'Pilates'), ('dance', 'Dance'), ('boxing', 'Boxing'), ('climbing', 'Climbing'), ('meditation', 'Meditation'), ('social', 'Social Gathering'), ('workshop', 'Workshop')], max_length=50)),
                ('vibe', models.CharField(choices=[('chill', 'Chill'), ('social', 'Social'), ('intense', 'Intense'), ('beginner_friendly', 'Beginner Friendly'), ('advanced', 'Advanced')], default='social', max_length=50)),
                ('location_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('max_attendees', models.PositiveIntegerField(default=50)),
                ('price_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_covers/')),
                ('what_to_bring', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-start_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_invitations',
            },
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('vibe_tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_reviews',
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('not_going', 'Not Going'), ('waitlist', 'Waitlist')], default='going', max_length=20)),
                ('guests_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rsvps',
            },
        ),
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_events',
            },
        ),
    ]
