# Generated by Django 6.0.3 on 2026-03-16 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='club_covers/')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('club_type', models.CharField(choices=[('cycling', 'Cycling Club'), ('running', 'Running Club'), ('yoga', 'Yoga Studio'), ('gym', 'Gym/Fitness Center'), ('outdoor', 'Outdoor Adventure'), ('wellness', 'Wellness Community'), ('social', 'Social Fitness'), ('other', 'Other')], default='other', max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clubs',
                'ordering': ['-member_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned')], default='active', max_length=20)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'club_memberships',
            },
        ),
        migrations.CreateModel(
            name='EventStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_rsvps', models.PositiveIntegerField(default=0)),
                ('going_count', models.PositiveIntegerField(default=0)),
                ('maybe_count', models.PositiveIntegerField(default=0)),
                ('not_going_count', models.PositiveIntegerField(default=0)),
                ('waitlist_count', models.PositiveIntegerField(default=0)),
                ('check_ins', models.PositiveIntegerField(default=0)),
                ('check_in_rate', models.FloatField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('invitations_sent', models.PositiveIntegerField(default=0)),
                ('invitations_accepted', models.PositiveIntegerField(default=0)),
                ('attendee_age_avg', models.FloatField(blank=True, null=True)),
                ('attendee_gender_breakdown', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_stats',
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('warn', 'Warning'), ('mute', 'Mute'), ('ban', 'Ban'), ('content_remove', 'Content Removal'), ('account_suspend', 'Account Suspension'), ('account_delete', 'Account Deletion'), ('promote_super', 'Promote to Super User'), ('demote_super', 'Demote from Super User')], max_length=50)),
                ('reason', models.TextField()),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'moderation_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('match', 'New Match'), ('message', 'New Message'), ('event_reminder', 'Event Reminder'), ('event_invite', 'Event Invitation'), ('rsvp_confirmation', 'RSVP Confirmation'), ('workout_milestone', 'Workout Milestone'), ('follow', 'New Follower'), ('wave', 'New Wave'), ('system', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_users_daily', models.PositiveIntegerField(default=0)),
                ('active_users_weekly', models.PositiveIntegerField(default=0)),
                ('active_users_monthly', models.PositiveIntegerField(default=0)),
                ('total_workouts_logged', models.PositiveIntegerField(default=0)),
                ('total_events_created', models.PositiveIntegerField(default=0)),
                ('total_rsvps', models.PositiveIntegerField(default=0)),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('day_1_retention', models.FloatField(default=0)),
                ('day_7_retention', models.FloatField(default=0)),
                ('day_30_retention', models.FloatField(default=0)),
                ('total_distance_km', models.FloatField(default=0)),
                ('total_duration_seconds', models.PositiveBigIntegerField(default=0)),
                ('total_calories_burned', models.PositiveBigIntegerField(default=0)),
                ('event_check_ins', models.PositiveIntegerField(default=0)),
                ('average_event_rating', models.FloatField(default=0)),
                ('new_matches', models.PositiveIntegerField(default=0)),
                ('match_acceptance_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('profile_view', 'Profile View'), ('workout_log', 'Workout Log'), ('event_view', 'Event View'), ('event_rsvp', 'Event RSVP'), ('event_checkin', 'Event Check-in'), ('match_view', 'Match View'), ('match_action', 'Match Action'), ('message_sent', 'Message Sent'), ('settings_change', 'Settings Change')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
