# Generated by Django 6.0.3 on 2026-03-16 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('fit_buddy', 'Fit Buddy'), ('vibe_check', 'Vibe Check'), ('community', 'Community Connector')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('compatibility_score', models.FloatField(blank=True, null=True)),
                ('shared_interests', models.JSONField(blank=True, default=list)),
                ('icebreaker_sent', models.BooleanField(default=False)),
                ('icebreaker_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compatibility_score', models.FloatField()),
                ('reason', models.CharField(choices=[('shared_interests', 'Shared Interests'), ('same_events', 'Attending Same Events'), ('location', 'Nearby Location'), ('activity_match', 'Activity Match'), ('goal_alignment', 'Goal Alignment'), ('mutual_friends', 'Mutual Connections')], max_length=50)),
                ('reason_details', models.TextField(blank=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_acted_on', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'match_suggestions',
                'ordering': ['-compatibility_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('swipe_type', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass'), ('super_like', 'Super Like')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'swipes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDiscoverySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discoverable', models.BooleanField(default=True)),
                ('show_me_to', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('all', 'All')], default='all', max_length=20)),
                ('show_me', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('all', 'All')], default='all', max_length=20)),
                ('min_age', models.PositiveIntegerField(default=18)),
                ('max_age', models.PositiveIntegerField(default=65)),
                ('max_distance_km', models.PositiveIntegerField(default=50)),
                ('looking_for_fitness_buddy', models.BooleanField(default=True)),
                ('looking_for_romantic', models.BooleanField(default=True)),
                ('looking_for_community', models.BooleanField(default=True)),
                ('preferred_activities', models.JSONField(blank=True, default=list)),
                ('min_experience_level', models.CharField(choices=[('any', 'Any Level'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='any', max_length=20)),
                ('match_availability', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_discovery_settings',
            },
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waves',
                'ordering': ['-created_at'],
            },
        ),
    ]
