# Generated by Django 6.0.3 on 2026-03-16 21:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('cycling', 'Cycling'), ('running', 'Running'), ('walking', 'Walking'), ('yoga', 'Yoga'), ('strength', 'Strength Training'), ('swimming', 'Swimming'), ('hiking', 'Hiking'), ('pilates', 'Pilates'), ('dance', 'Dance'), ('boxing', 'Boxing'), ('climbing', 'Climbing'), ('meditation', 'Meditation'), ('hiit', 'HIIT'), ('crossfit', 'CrossFit'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('distance_km', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('elevation_gain_m', models.FloatField(blank=True, null=True)),
                ('elevation_loss_m', models.FloatField(blank=True, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('max_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_speed_kmh', models.FloatField(blank=True, null=True)),
                ('max_speed_kmh', models.FloatField(blank=True, null=True)),
                ('avg_cadence', models.PositiveIntegerField(blank=True, null=True)),
                ('max_cadence', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_power', models.PositiveIntegerField(blank=True, null=True)),
                ('max_power', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('strava', 'Strava'), ('apple_health', 'Apple Health'), ('google_fit', 'Google Fit'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin')], default='manual', max_length=50)),
                ('external_id', models.CharField(blank=True, help_text='External platform workout ID', max_length=255)),
                ('gps_data', models.JSONField(blank=True, default=dict, help_text='GPS coordinates and timestamps')),
                ('is_shared', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workouts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('fastest_5k', 'Fastest 5K'), ('fastest_10k', 'Fastest 10K'), ('half_marathon', 'Half Marathon'), ('marathon', 'Marathon'), ('longest_ride', 'Longest Ride'), ('max_power', 'Max Power'), ('max_speed', 'Max Speed'), ('longest_workout', 'Longest Workout'), ('most_calories', 'Most Calories Burned')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('achieved_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workout')),
            ],
            options={
                'db_table': 'personal_records',
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_comments', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workouts.workout')),
            ],
            options={
                'db_table': 'workout_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('weekly_workouts', 'Weekly Workouts'), ('weekly_distance', 'Weekly Distance (km)'), ('weekly_duration', 'Weekly Duration (minutes)'), ('monthly_workouts', 'Monthly Workouts'), ('monthly_distance', 'Monthly Distance (km)'), ('streak_days', 'Workout Streak (days)')], max_length=50)),
                ('target_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current_value', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='workout_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='workouts', to='workouts.workoutphoto'),
        ),
        migrations.CreateModel(
            name='WorkoutStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_workout_date', models.DateField(blank=True, null=True)),
                ('streak_started_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_streaks',
            },
        ),
        migrations.CreateModel(
            name='WorkoutLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_likes', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='workouts.workout')),
            ],
            options={
                'db_table': 'workout_likes',
                'unique_together': {('workout', 'user')},
            },
        ),
    ]
