# Generated by Django 6.0.3 on 2026-03-17 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPXRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('route_points', models.JSONField(help_text='Array of {lat, lng, elevation} points')),
                ('total_distance_km', models.FloatField()),
                ('total_elevation_gain_m', models.FloatField(default=0)),
                ('activity_type', models.CharField(choices=[('cycling', 'Cycling'), ('running', 'Running'), ('walking', 'Walking'), ('yoga', 'Yoga'), ('strength', 'Strength Training'), ('swimming', 'Swimming'), ('hiking', 'Hiking'), ('pilates', 'Pilates'), ('dance', 'Dance'), ('boxing', 'Boxing'), ('climbing', 'Climbing'), ('meditation', 'Meditation'), ('hiit', 'HIIT'), ('crossfit', 'CrossFit'), ('other', 'Other')], default='cycling', max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpx_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gpx_routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveWorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('cycling', 'Cycling'), ('running', 'Running'), ('walking', 'Walking'), ('yoga', 'Yoga'), ('strength', 'Strength Training'), ('swimming', 'Swimming'), ('hiking', 'Hiking'), ('pilates', 'Pilates'), ('dance', 'Dance'), ('boxing', 'Boxing'), ('climbing', 'Climbing'), ('meditation', 'Meditation'), ('hiit', 'HIIT'), ('crossfit', 'CrossFit'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_paused_seconds', models.PositiveIntegerField(default=0)),
                ('current_distance_km', models.FloatField(default=0)),
                ('current_duration_seconds', models.PositiveIntegerField(default=0)),
                ('current_speed_kmh', models.FloatField(blank=True, null=True)),
                ('current_cadence', models.PositiveIntegerField(blank=True, null=True)),
                ('current_power', models.PositiveIntegerField(blank=True, null=True)),
                ('current_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('current_altitude', models.FloatField(blank=True, null=True)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('route_points', models.JSONField(default=list, help_text='Array of {lat, lng, timestamp, altitude, speed} objects')),
                ('is_live_shared', models.BooleanField(default=False, help_text='Share live location with friends')),
                ('final_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_session', to='workouts.workout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_workout_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
